"""added column photo

Revision ID: 3cf91990a859
Revises: 4188e87902b0
Create Date: 2023-08-22 17:47:10.251758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3cf91990a859'
down_revision: Union[str, None] = '4188e87902b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', sa.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###
