"""change type

Revision ID: 74cc750ad0e3
Revises: 3cf91990a859
Create Date: 2023-08-22 22:00:37.966577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '74cc750ad0e3'
down_revision: Union[str, None] = '3cf91990a859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "photo", type_=sa.TEXT)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
